In [1]:
import numpy as np

In [2]:
#2-D array
climate_data=np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    
    [102,43,37],
    [69,96,70]
    
]) 

In [3]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [4]:
climate_data.shape

(5, 3)

In [10]:
#3-D array
arr_3=np.array([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [18,19,20.5]]
        
   
    
])

In [11]:
arr_3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [18. , 19. , 20.5]]])

In [7]:
arr_3.shape

(2, 2, 3)

In [9]:
type(climate_data)

numpy.ndarray

In [13]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])