In [2]:
import numpy as np

In [3]:
climate_data=np.array([
    [73,67,43],
    [91,88,64],
    [87,134,58],
    [102,43,37],
    [69,96,70]
])

In [4]:
weight=np.array([0.3,0.2,0.5])

In [5]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [7]:
weight

array([0.3, 0.2, 0.5])

In [10]:
#matrix multiplication with matmul function
np.matmul(climate_data,weight)


array([56.8, 76.9, 81.9, 57.7, 74.9])

In [12]:
#@ also works as a matrix multiplication
climate_data @ weight

array([56.8, 76.9, 81.9, 57.7, 74.9])