In [1]:
#download file
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x22881e897c8>)

In [3]:
import numpy as np

In [6]:
#genfromtxt function for read the file
climate_data=np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [7]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [8]:
climate_data.shape

(10000, 3)

In [9]:
weights=np.array([0.3,0.2,0.5])

In [10]:
yields=np.matmul(climate_data,weights)

In [11]:
print(yields)

[72.2 59.7 65.2 ... 71.1 80.7 73.4]


In [13]:
yields.shape

(10000,)

In [15]:
#in climate data there is 10000 rows but in yeilds there is only 1 rows so first we have to compatible it.so we have to reshape it  
yields.reshape(10000,1)

array([[72.2],
       [59.7],
       [65.2],
       ...,
       [71.1],
       [80.7],
       [73.4]])

In [16]:
yields.reshape(10000,1).shape

(10000, 1)

In [20]:
climate_results=np.concatenate((climate_data, yields.reshape(10000,1)),axis=1)

In [21]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [24]:
#now save this as a text
np.savetxt(
           'climate_results.txt',
           climate_results,
           fmt='%.2f',
           delimiter=',',
           header='temperature,rainfall,humidity,yield_apples',
           comments=''
    
            )